export const data = {
	id: 1,
	name: "Whispers of Infiltration",
	regionId: null,
	type: "faction",
	urgency: "urgent",
	visibility: "rumored",
	mood: "tense",
	description: [
		"Northern agents have infiltrated the region",
		"Covert intelligence gathering threatens local stability",
		"Subtle investigation required to uncover and neutralize the threat",
	],
	creativePrompts: [
		"Uncover the hidden network of northern spies",
		"Navigate complex social investigations",
		"Protect regional interests through discretion",
	],
	failureOutcomes: [
		"Northern agents continue gathering intelligence",
		"Potential future regional destabilization",
		"Loss of trust from The Whispered Thread",
	],
	successOutcomes: [
		"Northern spy network exposed",
		"Immediate threat to region neutralized",
		"Enhanced regional security",
	],
	objectives: [
		"Identify northern spy network",
		"Gather counterintelligence",
		"Prevent potential regional destabilization",
		"Minimize direct confrontation",
	],
	prerequisites: ["Initial contact with The Whispered Thread", "Demonstrate ability to operate discreetly"],
	rewards: [
		"Favor with The Whispered Thread",
		"Potential intelligence resources",
		"Regional recognition",
		"Monetary compensation",
	],
	themes: ["Subterfuge", "Information as power", "Diplomatic tension"],
	inspirations: [
		"Complex political intrigue",
		"Subtle intelligence gathering",
		"Nuanced social investigation",
	],
	items: [],
	region: null,
	requiredBy: [],
	requires: [],
	twists: [],
	factions: [],
	npcs: [
		{
			id: 1,
			npcId: 2,
			questId: 1,
			role: "Primary Information Source",
			importance: "major",
			description: [
				"Provides key initial intelligence",
				"Offers subtle guidance",
				"Connects party to deeper investigation",
			],
			creativePrompts: [
				"Navigate Eliana's complex information network",
				"Understand her subtle approach to intelligence",
			],
			dramaticMoments: [
				"Unexpected revelation about regional tensions",
				"Cryptic guidance that proves crucial",
			],
			hiddenAspects: [
				"Deeper connections to regional power structures",
				"Motivations beyond simple information gathering",
			],
			npc: {
				name: "Eliana Marko",
			},
		},
	],
	stages: [
		{
			id: 1,
			questId: 1,
			locationId: null,
			stage: 1,
			name: "Initial Intelligence Gathering",
			dramatic_question: "Can the party discretely identify potential northern agents?",
			description: [
				"Meet with Whispered Thread contact",
				"Begin initial investigations",
				"Gather first threads of information",
			],
			creativePrompts: [
				"Navigate complex social investigations",
				"Gather information through indirect means",
			],
			objectives: [
				"Make contact with Whispered Thread",
				"Identify potential sources of information",
				"Begin mapping potential spy network",
			],
			completionPaths: ["Successful discrete information gathering", "Identifying initial spy suspects"],
			encounters: [
				"Subtle marketplace interactions",
				"Careful social investigations",
				"Navigating complex information networks",
			],
			locations: ["Hermes' Crossroads Market", "Various marketplace locations"],
			dramatic_moments: [
				"Unexpected information revelation",
				"Potential risk of exposure",
				"First glimpse of larger conspiracy",
			],
			sensory_elements: [
				"Hushed marketplace conversations",
				"Tension in social interactions",
				"Subtle shifts in local dynamics",
			],
			clues: [],
			location: null,
			decisions: [],
			triggerConsequences: [],
			outgoingLinks: [
				{
					id: 1,
					questId: 1,
					fromStageId: 1,
					toStageId: 3,
					conditionType: "choice",
					dramatically_interesting: null,
					linkName: "Diplomatic Approach",
					conditionValue: "Pursue official diplomatic channels",
					successDescription: [
						"Successfully navigate diplomatic networks",
						"Gain access to official information sources",
					],
					failureDescription: [
						"Diplomatic approach potentially compromises investigation",
						"Risk of alerting potential targets",
					],
					narrativeTransition: [
						"Shift from marketplace gathering to formal diplomatic interactions",
						"Adjust investigation strategy to official protocols",
					],
					toStage: {
						id: 3,
						questId: 1,
						locationId: null,
						stage: 2,
						name: "Diplomatic Channels",
						dramatic_question:
							"Can the party navigate diplomatic channels without causing an international conflict?",
						description: [
							"Carefully maneuver through official diplomatic interactions",
							"Use official channels to uncover subtle information",
							"Maintain strict diplomatic protocols",
						],
						creativePrompts: [
							"Navigate complex diplomatic interactions",
							"Uncover hidden political motivations",
						],
						objectives: [
							"Navigate official diplomatic networks",
							"Gather intelligence through official channels",
							"Identify potential northern contacts",
						],
						completionPaths: [
							"Successfully identify diplomatic connections",
							"Uncover official communication networks",
						],
						encounters: [
							"Diplomatic negotiations",
							"Subtle information exchanges",
							"Careful political maneuvering",
						],
						locations: ["Local administrative centers", "Diplomatic quarters", "Official meeting halls"],
						dramatic_moments: [
							"Unexpected diplomatic revelation",
							"Potential risk of international incident",
							"Delicate information exchange",
						],
						sensory_elements: [
							"Formal diplomatic environments",
							"Subtle tension in official interactions",
							"Carefully measured conversations",
						],
						quest: {
							name: "Whispers of Infiltration",
						},
						slug: "diplomatic-channels",
					},
				},
				{
					id: 2,
					questId: 1,
					fromStageId: 1,
					toStageId: 4,
					conditionType: "choice",
					dramatically_interesting: null,
					linkName: "Underworld Investigation",
					conditionValue: "Pursue underground information networks",
					successDescription: [
						"Successfully infiltrate criminal networks",
						"Gain access to hidden information sources",
					],
					failureDescription: [
						"Underground approach may expose investigation",
						"Risk of violent confrontation",
					],
					narrativeTransition: [
						"Shift from marketplace gathering to dangerous underground interactions",
						"Adjust investigation to high-risk information gathering",
					],
					toStage: {
						id: 4,
						questId: 1,
						locationId: null,
						stage: 2,
						name: "Underworld Connections",
						dramatic_question: "Can the party survive and gather intelligence in the dangerous underground?",
						description: [
							"Navigate dangerous underground information networks",
							"Use criminal connections to uncover spy activities",
							"Maintain cover and avoid detection",
						],
						creativePrompts: ["Navigate criminal underworld", "Survive dangerous information gathering"],
						objectives: [
							"Infiltrate criminal networks",
							"Gather intelligence through underground sources",
							"Identify potential spy connections",
						],
						completionPaths: [
							"Successfully infiltrate underground networks",
							"Uncover criminal connections to northern agents",
						],
						encounters: [
							"Dangerous underground interactions",
							"Potential combat scenarios",
							"Risky information exchanges",
						],
						locations: ["Hidden taverns", "Underground meeting spots", "Shadowy marketplace corners"],
						dramatic_moments: [
							"Unexpected violent confrontation",
							"Betrayal by underground contact",
							"Narrow escape from dangerous situation",
						],
						sensory_elements: [
							"Tense underground environments",
							"Smell of alcohol and danger",
							"Hushed, threatening conversations",
						],
						quest: {
							name: "Whispers of Infiltration",
						},
						slug: "underworld-connections",
					},
				},
			],
			slug: "initial-intelligence-gathering",
		},
		{
			id: 7,
			questId: 1,
			locationId: 3,
			stage: 1,
			name: "Initial Market Intelligence",
			dramatic_question: "Can the party gather initial intelligence without alerting potential targets?",
			description: [
				"Begin gathering initial intelligence about potential northern agents",
				"Navigate marketplace social networks",
				"Collect initial information fragments",
			],
			creativePrompts: [
				"Navigate complex marketplace interactions",
				"Gather information through subtle means",
			],
			objectives: [
				"Identify potential sources of information",
				"Begin mapping potential spy network",
				"Maintain discretion during initial investigations",
			],
			completionPaths: [
				"Successfully identify initial information sources",
				"Build initial network of potential contacts",
			],
			encounters: [
				"Marketplace social interactions",
				"Subtle information exchanges",
				"Potential risk of exposure",
			],
			locations: ["Hermes' Crossroads Market", "Marketplace gathering points"],
			dramatic_moments: [
				"Unexpected information revelation",
				"Potential risk of being discovered",
				"First glimpse of larger conspiracy",
			],
			sensory_elements: [
				"Bustling marketplace sounds",
				"Tension in marketplace interactions",
				"Subtle shifts in conversation",
			],
			clues: [],
			location: {
				id: 3,
				regionId: 1,
				locationType: "market",
				name: "Hermes' Crossroads Market",
				terrain: "urban",
				climate: "mediterranean",
				creativePrompts: [
					"Negotiate a deal with a supernatural merchant",
					"Uncover a hidden magical artifact",
					"Navigate the market's mystical economy",
				],
				creatures: [
					"Merchants with supernatural bargaining skills",
					"Minor divine messengers",
					"Shapeshifting traders",
				],
				description: [
					"A bustling marketplace with winding stone paths",
					"Stalls that seem to appear and disappear mysteriously",
					"Mixture of mundane goods and mystical artifacts",
					"Constant hum of negotiation and magical whispers",
				],
				environment: null,
				features: [
					"Statues of Hermes at key intersections",
					"Hidden magical trading posts",
					"Shifting architectural layouts",
					"Magical currency exchange points",
				],
				treasures: [
					"Artifacts with hidden magical properties",
					"Rare mythological items",
					"Enchanted trade goods",
				],
				slug: "hermes-crossroads-market",
			},
			decisions: [],
			triggerConsequences: [],
			outgoingLinks: [],
			slug: "initial-market-intelligence",
		},
	],
}
