packages:
  - packages/*
catalog:
  "@types/better-sqlite3": ^7.6.12
  "@types/node": ^22.13.10
  better-sqlite3: ^11.9.1
  drizzle-orm: ^0.40.1
  drizzle-zod: ^0.7.0
  tailwindcss: ^4.0.14
  tsup: ^8.4.0
  typescript: ^5.8.2
  vitest: ^3.0.9
  zod: ^3.24.2
  tsx: ^4.19.3
