packages:
  - packages/*
catalog:
  "@types/node": ^22.13.10
  drizzle-orm: ^0.41.0
  drizzle-zod: ^0.7.1
  tailwindcss: ^4.0.14
  tsup: ^8.4.0
  typescript: ^5.8.2
  vitest: ^3.0.9
  zod: ^3.24.2
  tsx: ^4.19.3
