export const testData = {
	id: 1,
	name: "Paphos",
	dangerLevel: "moderate",
	type: "city",
	economy: "Tourism, fishing, agriculture, and temple offerings",
	history:
		"Founded according to legend where Aphrodite first emerged from the sea, Paphos has long been a spiritual center. Now it stands as the last major refugee center for those fleeing the northern corruption.",
	population:
		"A swelling population of approximately 60,000, with nearly half being refugees from northern areas.",
	culturalNotes: [
		"Religious practices honoring Aphrodite remain central to daily life",
		"A mixing pot of traditional Cypriot culture and desperate northern refugees",
		"Festivals celebrating Adonis and Aphrodite continue despite the crisis",
		"Traditional Cypriot cuisine has evolved with limited resources",
		"Strong maritime tradition with fishing boats doubling as scouts",
	],
	description: [
		"Sits on the southwestern coast of Cyprus, with ancient stone buildings and newer wooden structures built to accommodate refugees",
		"Famous for the Temple of Aphrodite which glows with faint divine magic at night",
		"Surrounded by defensive walls that have been hastily reinforced",
		"Harbor filled with fishing vessels and the occasional merchant ship brave enough to still trade",
		"Vineyards and olive groves still produce on the outskirts, though many farmers now carry weapons while tending their crops",
	],
	creativePrompts: [
		"What ancient divine secrets might still be hidden beneath the Temple of Aphrodite?",
		"How are tensions developing between longtime residents and desperate refugees?",
		"What omens or signs from the gods have appeared in recent days?",
		"Which refugees might carry important knowledge about the northern enemy?",
		"What spies or corrupted individuals might have infiltrated the city?",
	],
	hazards: [
		"Occasional monster raids from northern territories",
		"Food shortages creating social tensions",
		"Abandoned wells tainted by unknown corruption",
		"Cultists of Typhon attempting to infiltrate and sabotage defenses",
		"Seasonal storms growing increasingly violent and unnatural",
	],
	pointsOfInterest: [
		"The grand Temple of Aphrodite overlooking the sea",
		"The refugee quarter with makeshift shelters and markets",
		"The fortified harbor with watchtowers",
		"The Council Chambers where leaders debate the crisis",
		"The Tomb of Kings, ancient burial site now used for emergency shelter",
	],
	rumors: [
		"Aphrodite's tears fall as real pearls in the temple during new moons",
		"A secret passage beneath the Tomb of Kings leads to a safe haven",
		"The northern corruption cannot cross running water",
		"Children born since the invasion sometimes exhibit strange birthmarks resembling divine symbols",
		"Fish caught beyond the bay sometimes carry messages in their bellies from coastal settlements",
	],
	secrets: [
		"An ancient artifact that could repel the corruption lies forgotten in a sea cave",
		"Several council members have been partially corrupted but fight the influence",
		"The Temple of Aphrodite stands on a nexus of divine energy that could be weaponized",
		"Descendants of Adonis with divine blood live unknown among the refugees",
		"The true nature of the northern corruption is tied to a betrayal among the Greek pantheon",
	],
	security: [
		"City Guard bolstered by refugee volunteers",
		"Priestesses of Aphrodite maintain magical wards around the temple district",
		"Naval patrols scout the coastline for approaching threats",
		"Messenger birds trained to warn of approaching danger",
		"Mercenary groups hired to defend the outlying farms and vineyards",
	],
	incomingRelations: [],
	outgoingRelations: [
		{
			id: 1,
			regionId: 1,
			otherRegionId: 2,
			relationType: "defensive border",
			description: [
				"The border between Paphos and the Akamas Peninsula is heavily patrolled by the Paphos City Guard",
				"Several watchtowers monitor activity in the peninsula",
				"Refugees fleeing through this area are quarantined and checked for corruption",
				"Occasional skirmishes occur when creatures from Akamas venture too close to Paphos",
				"Several small farming communities exist in this buffer zone, heavily fortified",
			],
			creativePrompts: [
				"What happens to someone who shows signs of corruption at the checkpoints?",
				"How do farmers survive in these dangerous borderlands?",
				"What secrets might refugees bring regarding the true nature of the peninsula's corruption?",
				"Which guards might be susceptible to corruption after long exposure to the border?",
				"What illicit trade might exist between corrupted individuals and desperate Paphos citizens?",
			],
			targetRegion: {
				name: "Akamas Peninsula",
				id: 2,
			},
			connections: [
				{
					id: 1,
					relationId: 1,
					routeType: "road",
					travelDifficulty: "moderate",
					travelTime: "Half a day on foot, a few hours by horse",
					controllingFaction: null,
					travelHazards: [
						"Corrupted wildlife occasionally attacking travelers",
						"Typhonic patrols searching for sacrifices or infiltrators",
						"Sections of road damaged by earthquakes caused by the corruption",
						"Mist pockets that can cause disorientation and hallucinations",
						"Desperate bandits preying on refugees",
					],
					pointsOfInterest: [
						"The Guardian's Rest - a shrine to Hermes that offers safe haven",
						"The Quarantine Checkpoint where travelers are inspected for corruption",
						"The Broken Bridge requiring a detour through more dangerous terrain",
						"The Three Sisters - a trio of hills topped with watchtowers",
						"The Last Farm - the final outpost before entering corrupted lands",
					],
					description: [
						"An ancient coastal road that once served merchants and pilgrims",
						"Now fortified with barricades and checkpoints at regular intervals",
						"Parts of the road show signs of corruption - cracked stones with strange growths",
						"Prayer stations to Aphrodite and Apollo line the safer sections",
						"Ditches on either side are filled with purifying salt water",
						"Warning markers indicate dangerous areas where the road comes too close to corrupted zones",
					],
					creativePrompts: [
						"What creatures might lurk just out of sight of the road?",
						"What changes might travelers notice in themselves after journeying through corrupted areas?",
						"How do the guards at checkpoints identify corruption?",
						"What remnants of normal life might still be visible along the abandoned sections?",
						"What omens or signs might travelers encounter that foreshadow danger?",
					],
				},
			],
		},
	],
	locations: [
		{
			id: 1,
			regionId: 1,
			locationType: "temple",
			name: "Temple of Aphrodite",
			terrain: "Coastal cliffs",
			climate: "Mediterranean, warm and mild",
			mood: "Sacred, hopeful, tense",
			environment: "Urban sanctuary",
			creativePrompts: [
				"What ancient rituals might help protect against Typhonic corruption?",
				"How has the Temple adapted to serve as both a religious site and strategic headquarters?",
				"What divine omens have the priestesses witnessed in recent days?",
				"Which artifact might be hidden in the temple's depths?",
				"How has Aphrodite's presence manifested during the crisis?",
			],
			creatures: [
				"Doves sacred to Aphrodite that act as messengers",
				"Temple guardians - animated bronze statues of ancient heroes",
				"Oracle serpents that whisper prophecies",
				"Refugee priests and priestesses from fallen northern temples",
				"Wounded warriors recovering through divine healing",
			],
			description: [
				"An imposing marble structure overlooking the sea, glowing with soft pink light at dawn and dusk",
				"Ancient columns adorned with gold and mother-of-pearl inlay",
				"Central sanctuary housing a statue of Aphrodite rising from the sea",
				"Inner chambers converted to planning rooms and refugee housing",
				"Gardens with medicinal and sacred plants tended by priestesses",
				"Secret underground chambers containing ancient artifacts and rituals",
			],
			features: [
				"The Eternal Flame - said to have been lit by Aphrodite herself",
				"The Pearl Pool where offerings are made",
				"The Oracle Chamber where priestesses commune with the goddess",
				"The Wall of Names - recording those lost to the northern corruption",
				"The Divine Armory where blessed weapons are stored",
				"The Sanctuary Bell that can be heard throughout Paphos",
			],
			treasures: [
				"The Girdle of Aphrodite - grants charisma and protection against corruption",
				"Tears of Adonis - pearls with healing properties",
				"Ancient scrolls containing forgotten rites of protection",
				"Blessed water from the Pearl Pool that temporarily repels corrupted creatures",
				"Bronze daggers with blades that glow in the presence of corruption",
			],
			lightingDescription: [
				"Soft, warm light filters through rose-colored crystal windows",
				"Enchanted shells embedded in walls glow with gentle illumination",
				"Ceremonial braziers burning sacred oils cast moving shadows",
				"The statue of Aphrodite seems to radiate its own pearlescent light",
				"Dawn and dusk bring a supernatural glow to the entire structure",
			],
			soundscape: [
				"Soft chanting of priestesses performing rituals",
				"The gentle splash of water in sacred pools",
				"Doves cooing in the rafters",
				"The crystalline ring of ceremonial bells",
				"The distant crash of waves against the cliffs below",
				"Whispered prayers of supplicants seeking divine aid",
			],
			smells: [
				"Burning myrrh and frankincense",
				"Fresh roses and sacred flowers",
				"Salt air from the sea",
				"Sweet wine used in libations",
				"Holy oil used to anoint warriors and priestesses",
				"Fragrant woods burning in braziers",
			],
			weather: [
				"Sea breezes keeping the air fresh and cool",
				"Occasional magical mists that form protective barriers",
				"Rain that sometimes falls as rose petals during important ceremonies",
				"Clear skies above even when storms rage elsewhere",
				"Sunlight that seems to linger longer here than elsewhere in the city",
			],
			descriptors: ["Sacred", "Ancient", "Luminous", "Hopeful", "Strategic", "Divine", "Protective"],
			region: {
				name: "Paphos",
				id: 1,
			},
			encounters: [],
			secrets: [],
			incomingRelations: [],
			outgoingRelations: [],
			items: [],
			npcs: [],
		},
		{
			id: 2,
			regionId: 1,
			locationType: "building",
			name: "The Sentinel's Rest",
			terrain: "Urban",
			climate: "Mediterranean",
			mood: "Vigilant camaraderie",
			environment: "Urban tavern and safehouse",
			creativePrompts: [
				"What secret meetings might take place in the hidden basement?",
				"How do new refugees react to the mix of soldiers and civilians?",
				"What information might be overheard at the bar after a few drinks?",
				"How does Theseus use this place to recruit promising individuals?",
				"What divine protections might be subtly worked into the structure?",
			],
			creatures: [
				"Off-duty Sentinel soldiers sharing stories",
				"Refugees seeking news of northern territories",
				"Resistance agents exchanging coded messages",
				"Local merchants selling supplies",
				"Priestesses taking rare moments of relaxation",
				"Scouts returning with reports from border regions",
				"Traveling performers offering respite through entertainment",
			],
			description: [
				"A three-story stone building with reinforced wooden doors",
				"Former merchant guild hall converted to a tavern and safehouse",
				"Main floor features a large common room with a circular bar",
				"Second floor has private meeting rooms and guest quarters",
				"Top floor serves as an observation post with views of the harbor",
				"Hidden basement accessible through a secret door behind the kitchen",
				"Walls adorned with maps of Cyprus and trophies from successful missions",
			],
			features: [
				"Massive hearth where a sacred flame is always kept burning",
				"Memorial wall with tokens from fallen Sentinels",
				"Bar made from the hull of a fishing boat that escaped the north",
				"Seven Company Table - a round table reserved for Sentinel captains",
				"Hidden weapons caches throughout the building",
				"Magical communication device in the observation room",
				"Secret escape tunnel leading to the harbor",
			],
			treasures: [
				"Collection of maps showing safe routes through corrupted territories",
				"Bottles of rare pre-invasion wine from northern vineyards",
				"Sentinel badges that serve as identification and minor magical protection",
				"Logbook containing coded intelligence reports",
				"Small shrine with votive offerings to various deities",
				"Experimental anti-corruption weapons stored in locked cases",
				"Ancient Cypriot artifacts rescued from northern temples",
			],
			lightingDescription: [
				"Warm amber lanterns hanging from exposed beams",
				"Enchanted torches that burn with steady flame regardless of drafts",
				"Stained glass windows depicting the patron deities of Cyprus",
				"Strategic skylights that illuminate the central bar",
				"Blackout shutters that can quickly darken the building",
				"Signal fire basket on the roof for emergency communications",
				"Soft divine light emanating from the hearth's eternal flame",
			],
			soundscape: [
				"Constant background murmur of conversation and planning",
				"Occasional bursts of laughter or singing",
				"Clinking of glasses and plates",
				"Boots on wooden floors and stone steps",
				"The crackle of the eternal flame in the hearth",
				"Muted weapon practice from the small courtyard behind",
				"Sentinel whistles and codes used by messengers",
			],
			smells: [
				"Roasting meat and fresh baked bread",
				"Local wine and strong Cypriot coffee",
				"Aromatic herbs used in traditional dishes",
				"Faint incense from the small shrine",
				"Weapon oil and leather from soldiers' gear",
				"Salt air from the nearby harbor",
				"Medicinal herbs used to treat wounded Sentinels",
			],
			weather: [
				"Protected from elements but open windows allow sea breezes",
				"Hearth keeps the space warm on cooler evenings",
				"Lower temperature in the stone basement for food storage",
				"Warm and sometimes stuffy during busy nights",
				"Rain collection system on the roof for fresh water",
			],
			descriptors: ["Strategic", "Welcoming", "Vigilant", "Sacred", "Resilient", "Communal", "Defiant"],
			region: {
				name: "Paphos",
				id: 1,
			},
			encounters: [],
			secrets: [],
			incomingRelations: [],
			outgoingRelations: [],
			items: [],
			npcs: [],
		},
		{
			id: 4,
			regionId: 1,
			locationType: "temple",
			name: "Petra tou Romiou (Aphrodite's Birthplace)",
			terrain: "Rocky coastline with distinctive sea stacks",
			climate: "Mediterranean coastal",
			mood: "Sacred, timeless, mystical",
			environment: "Coastal sacred site",
			creativePrompts: [
				"What signs might appear when the corruption approaches this sacred place?",
				"How does the divine energy here react differently to different visitors?",
				"What ancient ritual linked to the seven artifacts might be performed here?",
				"What prophetic visions might someone receive while meditating at this site?",
				"How might this location be the key to ending the corruption permanently?",
			],
			creatures: [
				"White doves sacred to Aphrodite",
				"Pristine sea creatures that approach visitors without fear",
				"Priestesses maintaining the sacred site",
				"Sentinel guards protecting the location",
				"Pilgrims seeking divine blessing",
				"Ghostly apparitions visible at specific astronomic alignments",
				"Ancient guardian spirits bound to protect the site",
			],
			description: [
				"Dramatic coastal formation where myth says Aphrodite emerged from sea foam",
				"Sacred beach with unique pink-tinged sand and crystal-clear waters",
				"Ancient ritual spaces carved into the coastal cliffs",
				"Hidden underwater caverns containing primordial divine energy",
				"Natural rock formations that resemble feminine forms from certain angles",
				"Shrines built into the coastline dating back thousands of years",
				"Protected by both physical Sentinel guards and ancient divine wards",
			],
			features: [
				"Massive limestone sea stacks rising from the water",
				"Hidden cave beneath the waterline accessible only at low tide",
				"Ancient altar carved into the coastal rocks",
				"Natural pools that fill with seawater said to have healing properties",
				"Crystalline formations that glow at moonrise",
				"Sacred grove on the cliff above with trees older than recorded history",
				"Seven pillars arranged in a specific astronomical pattern",
			],
			treasures: [
				"The Birth Shell - a perfect conch said to have cradled Aphrodite",
				"Waters with healing and cleansing properties",
				"Ancient inscriptions detailing forgotten rituals",
				"Star crystals that fall from the sky during meteor showers",
				"Divine essence that naturally collects in specific locations",
				"Votive offerings from thousands of years of worship",
				"The Font of Purity - a hidden shrine that can cleanse corruption",
			],
			lightingDescription: [
				"Natural sunlight that creates spectacular golden reflections off the water",
				"Moonlight that follows special paths across the rocks",
				"Bioluminescent waters that glow on sacred nights",
				"Light that seems to linger longer than it should at sunset",
				"Starlight reflected in pools with unusual clarity",
				"Soft ambient glow emanating from the ancient altar",
				"Rare phenomenon of pink-tinged light during specific astronomical alignments",
			],
			soundscape: [
				"The rhythmic crashing of waves",
				"Soft chanting from priestesses performing rituals",
				"Wind creating musical tones through natural rock formations",
				"Distant dolphin calls that seem to respond to prayers",
				"Perfect natural acoustics that carry whispered prayers",
				"Crystalline tones when certain rocks are touched",
				"Complete, profound silence that occasionally falls over the entire area",
			],
			smells: [
				"Salt air and sea spray",
				"Sweet floral scent with no visible source",
				"Ancient stone warmed by the sun",
				"Subtle divine perfume that changes based on the visitor",
				"Clean ozone after ritual magic",
				"Mineral-rich water from sacred pools",
				"Incense from pilgrim offerings",
			],
			weather: [
				"Unusually calm waters around the sacred rocks",
				"Mists that form at dawn and dusk resembling feminine forms",
				"Sunlight that creates rainbow effects through sea spray",
				"Clear skies even when storms rage nearby",
				"Star reflections in the water that sometimes move independently",
				"Gentle breezes that carry whispered words",
				"Occasional appearances of ghostly foam resembling the goddess's birth",
			],
			descriptors: ["Sacred", "Primordial", "Pristine", "Divine", "Timeless", "Powerful", "Harmonious"],
			region: {
				name: "Paphos",
				id: 1,
			},
			encounters: [],
			secrets: [],
			incomingRelations: [
				{
					id: 1,
					locationId: 5,
					otherLocationId: 4,
					description: [
						"The Garden of Rebirth was created using water from Petra tou Romiou",
						"Both locations were sacred to different aspects of the same divine power",
						"Underground channels still connect the Bloodspring to the sea near Aphrodite's Birthplace",
						"Both locations respond to the same lunar and stellar alignments",
						"Ancient rituals required simultaneous actions at both sites",
						"The artifacts resonate differently when present at either location",
						"Divine energy flows in a circuit between these two sacred places",
						"Corruption cannot maintain a foothold in either location",
					],
					creativePrompts: [
						"What happens when the same divine ritual is performed at both locations simultaneously?",
						"How might awakening ceremonies be enhanced by this connection?",
						"What ancient knowledge about this connection has been lost?",
						"How could this connection be used in the cleansing ritual?",
						"What happens when a person with divine blood visits both locations on the same day?",
					],
					relationType: "ancient sacred connection",
					sourceLocation: {
						id: 5,
						regionId: 1,
						locationType: "cave",
						name: "The Garden of Rebirth",
						terrain: "Underground garden complex",
						climate: "Artificially maintained Mediterranean perfection",
						mood: "Secret, mystical, ancient",
						environment: "Underground sanctuary and research facility",
						creativePrompts: [
							"What happens when an artifact is brought into the garden for the first time?",
							"How might the garden react to those with strong divine blood?",
							"What ancient secrets might be revealed in the garden's deepest chambers?",
							"How does the garden protect itself from discovery or intrusion?",
							"What unexpected properties might the Bloodspring water have?",
						],
						creatures: [
							"Members of the Children of Adonis in various stages of awakening",
							"Research subjects undergoing divine activation",
							"Caretakers with specialized plant abilities",
							"Small birds and butterflies that serve as messengers",
							"Ancient guardian constructs disguised as statues",
							"Specially bred plants with semi-consciousness",
							"Rare creatures thought extinct elsewhere in Cyprus",
						],
						description: [
							"Massive underground complex accessed through hidden entrances",
							"Ancient facility built thousands of years ago by early followers of Adonis",
							"Central chamber houses the Bloodspring where awakening rituals occur",
							"Research areas disguised as natural garden features",
							"Multiple levels connected by living plant stairways",
							"Sacred geometry encoded in the layout of planting beds",
							"Combination of ancient design and modern research equipment",
							"Records hall containing genealogies of divine bloodlines",
						],
						features: [
							"Central spring said to be blessed by Adonis's blood",
							"Seven garden sections arranged in a spiral pattern",
							"Ancient stone pedestals designed to hold the seven artifacts",
							"Living walls with plants growing in intricate patterns",
							"Carved stone benches positioned for meditation",
							"Complex irrigation system feeding from the central spring",
							"Glass ceiling panels allowing moonlight to enter on special nights",
							"Hidden research laboratory disguised among natural features",
						],
						treasures: [
							"Samples of every sacred plant in Cyprus",
							"Ancient texts on bloodline awakening",
							"Specially formulated herbal preparations that enhance divine abilities",
							"Seeds from plants believed extinct",
							"Blood samples from the strongest bloodlines",
							"Ritual implements used in awakening ceremonies",
							"Small-scale models of the seven artifacts",
						],
						lightingDescription: [
							"Crystal shafts channeling sunlight to specific garden areas",
							"Bioluminescent plants providing ambient illumination",
							"Ritual flames in copper basins that never need fuel",
							"Moonlight captured and amplified through ceiling apertures",
							"Soft golden glow from the central Bloodspring",
							"Shadow patterns created by plant silhouettes",
							"Specially positioned mirrors directing light to growing areas",
						],
						soundscape: [
							"Soft chanting from awakening rituals",
							"The gentle splash of the central spring",
							"Wind moving through sacred cypress trees",
							"Crystal resonance from the sunlight shafts",
							"The hum of ancient mechanisms maintaining the environment",
							"Soft footsteps on stone pathways",
							"Whispered conversations among researchers",
						],
						smells: [
							"Rich soil and growing things",
							"Sweet anemone blossoms",
							"Aromatic cypress wood",
							"Herbal preparations and medicines",
							"Ancient stone and mineral water",
							"Sacred oils used in rituals",
							"Subtle divine energy with a floral note",
						],
						weather: [
							"Precisely controlled temperature and humidity",
							"Artificial sunlight channeled through crystal shafts",
							"Occasional mist cycles providing moisture",
							"Perfect growing conditions year-round",
							"Specialized climate zones for different plants",
							"Seasonal variations simulated through ancient mechanisms",
							"Periodic releases of enriched air to sustain plant growth",
						],
						descriptors: ["Sacred", "Hidden", "Ancient", "Living", "Divine", "Harmonious", "Awakening"],
					},
				},
			],
			outgoingRelations: [],
			items: [],
			npcs: [],
		},
		{
			id: 5,
			regionId: 1,
			locationType: "cave",
			name: "The Garden of Rebirth",
			terrain: "Underground garden complex",
			climate: "Artificially maintained Mediterranean perfection",
			mood: "Secret, mystical, ancient",
			environment: "Underground sanctuary and research facility",
			creativePrompts: [
				"What happens when an artifact is brought into the garden for the first time?",
				"How might the garden react to those with strong divine blood?",
				"What ancient secrets might be revealed in the garden's deepest chambers?",
				"How does the garden protect itself from discovery or intrusion?",
				"What unexpected properties might the Bloodspring water have?",
			],
			creatures: [
				"Members of the Children of Adonis in various stages of awakening",
				"Research subjects undergoing divine activation",
				"Caretakers with specialized plant abilities",
				"Small birds and butterflies that serve as messengers",
				"Ancient guardian constructs disguised as statues",
				"Specially bred plants with semi-consciousness",
				"Rare creatures thought extinct elsewhere in Cyprus",
			],
			description: [
				"Massive underground complex accessed through hidden entrances",
				"Ancient facility built thousands of years ago by early followers of Adonis",
				"Central chamber houses the Bloodspring where awakening rituals occur",
				"Research areas disguised as natural garden features",
				"Multiple levels connected by living plant stairways",
				"Sacred geometry encoded in the layout of planting beds",
				"Combination of ancient design and modern research equipment",
				"Records hall containing genealogies of divine bloodlines",
			],
			features: [
				"Central spring said to be blessed by Adonis's blood",
				"Seven garden sections arranged in a spiral pattern",
				"Ancient stone pedestals designed to hold the seven artifacts",
				"Living walls with plants growing in intricate patterns",
				"Carved stone benches positioned for meditation",
				"Complex irrigation system feeding from the central spring",
				"Glass ceiling panels allowing moonlight to enter on special nights",
				"Hidden research laboratory disguised among natural features",
			],
			treasures: [
				"Samples of every sacred plant in Cyprus",
				"Ancient texts on bloodline awakening",
				"Specially formulated herbal preparations that enhance divine abilities",
				"Seeds from plants believed extinct",
				"Blood samples from the strongest bloodlines",
				"Ritual implements used in awakening ceremonies",
				"Small-scale models of the seven artifacts",
			],
			lightingDescription: [
				"Crystal shafts channeling sunlight to specific garden areas",
				"Bioluminescent plants providing ambient illumination",
				"Ritual flames in copper basins that never need fuel",
				"Moonlight captured and amplified through ceiling apertures",
				"Soft golden glow from the central Bloodspring",
				"Shadow patterns created by plant silhouettes",
				"Specially positioned mirrors directing light to growing areas",
			],
			soundscape: [
				"Soft chanting from awakening rituals",
				"The gentle splash of the central spring",
				"Wind moving through sacred cypress trees",
				"Crystal resonance from the sunlight shafts",
				"The hum of ancient mechanisms maintaining the environment",
				"Soft footsteps on stone pathways",
				"Whispered conversations among researchers",
			],
			smells: [
				"Rich soil and growing things",
				"Sweet anemone blossoms",
				"Aromatic cypress wood",
				"Herbal preparations and medicines",
				"Ancient stone and mineral water",
				"Sacred oils used in rituals",
				"Subtle divine energy with a floral note",
			],
			weather: [
				"Precisely controlled temperature and humidity",
				"Artificial sunlight channeled through crystal shafts",
				"Occasional mist cycles providing moisture",
				"Perfect growing conditions year-round",
				"Specialized climate zones for different plants",
				"Seasonal variations simulated through ancient mechanisms",
				"Periodic releases of enriched air to sustain plant growth",
			],
			descriptors: ["Sacred", "Hidden", "Ancient", "Living", "Divine", "Harmonious", "Awakening"],
			region: {
				name: "Paphos",
				id: 1,
			},
			encounters: [],
			secrets: [
				{
					id: 1,
					locationId: 5,
					secretType: "hidden area",
					difficultyToDiscover: "challenging",
					discoveryMethod: [
						"Following Sophia when she believes she's alone",
						"Noticing subtle differences in the flow of water from the Bloodspring",
						"Identifying plant patterns that form a map when viewed from above",
						"Sensing divine energy concentrating behind an apparently solid wall",
						"Finding references in ancient texts to an 'Inner Sanctum'",
						"Using awakened plant communication abilities to ask the oldest plants",
						"Observing the moonlight patterns during a specific lunar alignment",
					],
					description: [
						"The Inner Sanctum contains an eighth pedestal for an unknown artifact",
						"Ancient murals show Adonis's true connection to Typhon as divine opposites",
						"The chamber houses records of 'failed awakenings' and their consequences",
						"A preserved corrupted plant seems to be slowly healing rather than dying",
						"Diagrams suggest the artifacts can be used for purposes beyond what either faction knows",
						"Evidence that Sophia was not found but was born in this chamber",
						"The room contains a map showing additional divine bloodlines beyond Adonis",
					],
					creativePrompts: [
						"How might this discovery change the heroes' approach to the artifacts?",
						"What happens if Eleni discovers someone has found her secret research?",
						"How might the Children of Adonis react to outsiders knowing their deepest secrets?",
						"What connection might exist between Sophia's blood and the Bloodspring?",
						"How could this information be used to create a new approach to fighting corruption?",
					],
					consequences: [
						"Discovering the eighth pedestal changes understanding of the artifact quest",
						"Learning about the Adonis-Typhon connection reveals new cleansing possibilities",
						"Records of failed awakenings might provide critical warnings about current experiments",
						"The healing corrupted plant could provide breakthroughs in corruption treatment",
						"Alternative artifact uses might create conflict between factions",
						"Revelation of Sophia's true origin could change her place in prophecy",
						"Map of additional bloodlines could expand alliance possibilities",
					],
				},
			],
			incomingRelations: [],
			outgoingRelations: [
				{
					id: 1,
					locationId: 5,
					otherLocationId: 4,
					description: [
						"The Garden of Rebirth was created using water from Petra tou Romiou",
						"Both locations were sacred to different aspects of the same divine power",
						"Underground channels still connect the Bloodspring to the sea near Aphrodite's Birthplace",
						"Both locations respond to the same lunar and stellar alignments",
						"Ancient rituals required simultaneous actions at both sites",
						"The artifacts resonate differently when present at either location",
						"Divine energy flows in a circuit between these two sacred places",
						"Corruption cannot maintain a foothold in either location",
					],
					creativePrompts: [
						"What happens when the same divine ritual is performed at both locations simultaneously?",
						"How might awakening ceremonies be enhanced by this connection?",
						"What ancient knowledge about this connection has been lost?",
						"How could this connection be used in the cleansing ritual?",
						"What happens when a person with divine blood visits both locations on the same day?",
					],
					relationType: "ancient sacred connection",
					targetLocation: {
						id: 4,
						regionId: 1,
						locationType: "temple",
						name: "Petra tou Romiou (Aphrodite's Birthplace)",
						terrain: "Rocky coastline with distinctive sea stacks",
						climate: "Mediterranean coastal",
						mood: "Sacred, timeless, mystical",
						environment: "Coastal sacred site",
						creativePrompts: [
							"What signs might appear when the corruption approaches this sacred place?",
							"How does the divine energy here react differently to different visitors?",
							"What ancient ritual linked to the seven artifacts might be performed here?",
							"What prophetic visions might someone receive while meditating at this site?",
							"How might this location be the key to ending the corruption permanently?",
						],
						creatures: [
							"White doves sacred to Aphrodite",
							"Pristine sea creatures that approach visitors without fear",
							"Priestesses maintaining the sacred site",
							"Sentinel guards protecting the location",
							"Pilgrims seeking divine blessing",
							"Ghostly apparitions visible at specific astronomic alignments",
							"Ancient guardian spirits bound to protect the site",
						],
						description: [
							"Dramatic coastal formation where myth says Aphrodite emerged from sea foam",
							"Sacred beach with unique pink-tinged sand and crystal-clear waters",
							"Ancient ritual spaces carved into the coastal cliffs",
							"Hidden underwater caverns containing primordial divine energy",
							"Natural rock formations that resemble feminine forms from certain angles",
							"Shrines built into the coastline dating back thousands of years",
							"Protected by both physical Sentinel guards and ancient divine wards",
						],
						features: [
							"Massive limestone sea stacks rising from the water",
							"Hidden cave beneath the waterline accessible only at low tide",
							"Ancient altar carved into the coastal rocks",
							"Natural pools that fill with seawater said to have healing properties",
							"Crystalline formations that glow at moonrise",
							"Sacred grove on the cliff above with trees older than recorded history",
							"Seven pillars arranged in a specific astronomical pattern",
						],
						treasures: [
							"The Birth Shell - a perfect conch said to have cradled Aphrodite",
							"Waters with healing and cleansing properties",
							"Ancient inscriptions detailing forgotten rituals",
							"Star crystals that fall from the sky during meteor showers",
							"Divine essence that naturally collects in specific locations",
							"Votive offerings from thousands of years of worship",
							"The Font of Purity - a hidden shrine that can cleanse corruption",
						],
						lightingDescription: [
							"Natural sunlight that creates spectacular golden reflections off the water",
							"Moonlight that follows special paths across the rocks",
							"Bioluminescent waters that glow on sacred nights",
							"Light that seems to linger longer than it should at sunset",
							"Starlight reflected in pools with unusual clarity",
							"Soft ambient glow emanating from the ancient altar",
							"Rare phenomenon of pink-tinged light during specific astronomical alignments",
						],
						soundscape: [
							"The rhythmic crashing of waves",
							"Soft chanting from priestesses performing rituals",
							"Wind creating musical tones through natural rock formations",
							"Distant dolphin calls that seem to respond to prayers",
							"Perfect natural acoustics that carry whispered prayers",
							"Crystalline tones when certain rocks are touched",
							"Complete, profound silence that occasionally falls over the entire area",
						],
						smells: [
							"Salt air and sea spray",
							"Sweet floral scent with no visible source",
							"Ancient stone warmed by the sun",
							"Subtle divine perfume that changes based on the visitor",
							"Clean ozone after ritual magic",
							"Mineral-rich water from sacred pools",
							"Incense from pilgrim offerings",
						],
						weather: [
							"Unusually calm waters around the sacred rocks",
							"Mists that form at dawn and dusk resembling feminine forms",
							"Sunlight that creates rainbow effects through sea spray",
							"Clear skies even when storms rage nearby",
							"Star reflections in the water that sometimes move independently",
							"Gentle breezes that carry whispered words",
							"Occasional appearances of ghostly foam resembling the goddess's birth",
						],
						descriptors: ["Sacred", "Primordial", "Pristine", "Divine", "Timeless", "Powerful", "Harmonious"],
					},
				},
			],
			items: [],
			npcs: [
				{
					id: 1,
					npcId: 8,
					locationId: 5,
					description: [
						"Sophia maintains a private section of the garden dedicated to healing corrupted plants",
						"Frequently visits to commune with the Bloodspring for visions",
						"Has special access to restricted areas due to her research subject status",
						"Often tends to plants others find difficult to maintain",
						"Sometimes sleeps in the garden when experiencing intense prophetic dreams",
						"Uses the garden as a sanctuary when overwhelmed by her abilities",
						"Conducts her own secret awakening experiments in hidden corners",
					],
					creativePrompts: [
						"What unique plants has Sophia managed to grow that others cannot?",
						"How does the garden respond differently to her presence?",
						"What secrets has she discovered in the ancient records kept there?",
						"How might meeting characters in this setting change their perception of her?",
						"What corrupted plants is she secretly trying to heal, and why?",
					],
				},
			],
		},
	],
	quests: [],
	factions: [],
}

// Export the same data as unifyTestData to maintain compatibility
export const unifyTestData = testData
