ALTER TABLE "clues" ALTER COLUMN "quest_stage_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "faction_quest_involvement" ALTER COLUMN "quest_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "faction_regional_power" ALTER COLUMN "faction_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "npc_quest_roles" ALTER COLUMN "npc_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "quest_hook_npcs" ALTER COLUMN "hook_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "quest_hook_npcs" ALTER COLUMN "npc_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "quest_introductions" ALTER COLUMN "stage_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "region_connection_details" ALTER COLUMN "relation_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "conflict_participants" ALTER COLUMN "conflict_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "conflict_participants" ALTER COLUMN "faction_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "conflict_progression" ALTER COLUMN "conflict_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "conflict_progression" ALTER COLUMN "quest_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "faction_culture" ALTER COLUMN "faction_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "faction_diplomacy" ALTER COLUMN "faction_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "faction_diplomacy" ALTER COLUMN "other_faction_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "faction_headquarters" ALTER COLUMN "faction_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "faction_headquarters" ALTER COLUMN "site_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "faction_operations" ALTER COLUMN "faction_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "faction_regions" ALTER COLUMN "faction_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "arc_membership" ALTER COLUMN "arc_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "arc_membership" ALTER COLUMN "quest_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "character_relationships" ALTER COLUMN "npc_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "npc_factions" ALTER COLUMN "npc_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "npc_sites" ALTER COLUMN "npc_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "decision_outcomes" ALTER COLUMN "decision_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "quest_dependencies" ALTER COLUMN "quest_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "quest_stages" ALTER COLUMN "quest_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "quest_twists" ALTER COLUMN "quest_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "quest_unlock_conditions" ALTER COLUMN "quest_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "stage_decisions" ALTER COLUMN "quest_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "stage_decisions" ALTER COLUMN "from_stage_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "areas" ALTER COLUMN "region_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "region_connections" ALTER COLUMN "region_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "site_encounters" ALTER COLUMN "site_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "site_links" ALTER COLUMN "site_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "site_secrets" ALTER COLUMN "site_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "sites" ALTER COLUMN "area_id" SET NOT NULL;